### ISSUE TITLE
Rendering pauses when focusing another pane

### ISSUE THREAD

**Issue by Kjelli** [slammayjammay/hyper-postprocessing#22] opened 2019-09-23 08:59 UTC
I have four panes up, but only the one in focus renders, having both effects and writes paused in the other ones.

Is this by design? Is there any option to keep rendering writes to console even though the pane is not in focus?

**Comment by slammayjammay** [comment] 2019-09-27 05:52
That's not by design, just a big blind spot. I don't think there's much you can do on your end about it :(

**Comment by slammayjammay** [comment] 2020-03-01 03:38
Fixed in [v3](https://github.com/slammayjammay/hyper-postprocessing/releases/tag/v3.0.0)

**Closed by slammayjammay** 2020-03-01 03:38 UTC
